// Code generated by ogen, DO NOT EDIT.

package apprun

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateApplicationOperation             OperationName = "CreateApplication"
	CreateApplicationVersionOperation      OperationName = "CreateApplicationVersion"
	CreateAutoScalingGroupOperation        OperationName = "CreateAutoScalingGroup"
	CreateCertificateOperation             OperationName = "CreateCertificate"
	CreateClusterOperation                 OperationName = "CreateCluster"
	CreateLoadBalancerOperation            OperationName = "CreateLoadBalancer"
	DeleteApplicationOperation             OperationName = "DeleteApplication"
	DeleteApplicationVersionOperation      OperationName = "DeleteApplicationVersion"
	DeleteAutoScalingGroupOperation        OperationName = "DeleteAutoScalingGroup"
	DeleteCertificateOperation             OperationName = "DeleteCertificate"
	DeleteClusterOperation                 OperationName = "DeleteCluster"
	DeleteLoadBalancerOperation            OperationName = "DeleteLoadBalancer"
	GetApplicationOperation                OperationName = "GetApplication"
	GetApplicationContainersOperation      OperationName = "GetApplicationContainers"
	GetApplicationVersionOperation         OperationName = "GetApplicationVersion"
	GetAutoScalingGroupOperation           OperationName = "GetAutoScalingGroup"
	GetCertificateOperation                OperationName = "GetCertificate"
	GetClusterOperation                    OperationName = "GetCluster"
	GetLoadBalancerOperation               OperationName = "GetLoadBalancer"
	GetLoadBalancerNodeOperation           OperationName = "GetLoadBalancerNode"
	GetWorkerNodeOperation                 OperationName = "GetWorkerNode"
	ListApplicationVersionsOperation       OperationName = "ListApplicationVersions"
	ListApplicationsOperation              OperationName = "ListApplications"
	ListAutoScalingGroupsOperation         OperationName = "ListAutoScalingGroups"
	ListCertificateOperation               OperationName = "ListCertificate"
	ListClustersOperation                  OperationName = "ListClusters"
	ListLbServiceClassesOperation          OperationName = "ListLbServiceClasses"
	ListLoadBalancerNodesOperation         OperationName = "ListLoadBalancerNodes"
	ListLoadBalancersOperation             OperationName = "ListLoadBalancers"
	ListWorkerNodesOperation               OperationName = "ListWorkerNodes"
	ListWorkerServiceClassesOperation      OperationName = "ListWorkerServiceClasses"
	UpdateApplicationOperation             OperationName = "UpdateApplication"
	UpdateCertificateOperation             OperationName = "UpdateCertificate"
	UpdateClusterOperation                 OperationName = "UpdateCluster"
	UpdateWorkerNodeDrainingStateOperation OperationName = "UpdateWorkerNodeDrainingState"
)
