// Code generated by ogen, DO NOT EDIT.

package apprun

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBasicAuth handles BasicAuth security.
	HandleBasicAuth(ctx context.Context, operationName OperationName, t BasicAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesBasicAuth = map[string][]string{
	CreateApplicationOperation:             []string{},
	CreateApplicationVersionOperation:      []string{},
	CreateAutoScalingGroupOperation:        []string{},
	CreateCertificateOperation:             []string{},
	CreateClusterOperation:                 []string{},
	CreateLoadBalancerOperation:            []string{},
	DeleteApplicationOperation:             []string{},
	DeleteApplicationVersionOperation:      []string{},
	DeleteAutoScalingGroupOperation:        []string{},
	DeleteCertificateOperation:             []string{},
	DeleteClusterOperation:                 []string{},
	DeleteLoadBalancerOperation:            []string{},
	GetApplicationOperation:                []string{},
	GetApplicationContainersOperation:      []string{},
	GetApplicationVersionOperation:         []string{},
	GetAutoScalingGroupOperation:           []string{},
	GetCertificateOperation:                []string{},
	GetClusterOperation:                    []string{},
	GetLoadBalancerOperation:               []string{},
	GetLoadBalancerNodeOperation:           []string{},
	GetWorkerNodeOperation:                 []string{},
	ListApplicationVersionsOperation:       []string{},
	ListApplicationsOperation:              []string{},
	ListAutoScalingGroupsOperation:         []string{},
	ListCertificateOperation:               []string{},
	ListClustersOperation:                  []string{},
	ListLbServiceClassesOperation:          []string{},
	ListLoadBalancerNodesOperation:         []string{},
	ListLoadBalancersOperation:             []string{},
	ListWorkerNodesOperation:               []string{},
	ListWorkerServiceClassesOperation:      []string{},
	UpdateApplicationOperation:             []string{},
	UpdateCertificateOperation:             []string{},
	UpdateClusterOperation:                 []string{},
	UpdateWorkerNodeDrainingStateOperation: []string{},
}

func (s *Server) securityBasicAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BasicAuth
	if _, ok := findAuthorization(req.Header, "Basic"); !ok {
		return ctx, false, nil
	}
	username, password, ok := req.BasicAuth()
	if !ok {
		return nil, false, errors.New("invalid basic auth")
	}
	t.Username = username
	t.Password = password
	t.Roles = operationRolesBasicAuth[operationName]
	rctx, err := s.sec.HandleBasicAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BasicAuth provides BasicAuth security value.
	BasicAuth(ctx context.Context, operationName OperationName) (BasicAuth, error)
}

func (s *Client) securityBasicAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BasicAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BasicAuth\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
