// Code generated by ogen, DO NOT EDIT.

package apprun

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateApplication implements createApplication operation.
//
// 指定したクラスタに新しいアプリケーションを作成します。1アカウントにつき最大10個まで作成可能です。.
//
// POST /applications
func (UnimplementedHandler) CreateApplication(ctx context.Context, req *CreateApplication) (r *CreateApplicationResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateApplicationVersion implements createApplicationVersion operation.
//
// アプリケーションバージョンを作成します｡アプリケーションバージョンを作成するだけではノードにデプロイされません｡アプリケーションのアクティブバージョンに指定するとノードにデプロイされます｡.
//
// POST /applications/{applicationID}/versions
func (UnimplementedHandler) CreateApplicationVersion(ctx context.Context, req *CreateApplicationVersion, params CreateApplicationVersionParams) (r *CreateApplicationVersionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAutoScalingGroup implements createAutoScalingGroup operation.
//
// 新しい Auto Scaling Group を作成します。.
//
// POST /clusters/{clusterID}/asg
func (UnimplementedHandler) CreateAutoScalingGroup(ctx context.Context, req *CreateAutoScalingGroup, params CreateAutoScalingGroupParams) (r *CreateAutoScalingGroupResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCertificate implements createCertificate operation.
//
// 新しい証明書を作成します。.
//
// POST /clusters/{clusterID}/certificates
func (UnimplementedHandler) CreateCertificate(ctx context.Context, req *CreateCertificate, params CreateCertificateParams) (r *CreateCertificateResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCluster implements createCluster operation.
//
// 新しいクラスタを作成します。作成後にクラスタIDを返します。.
//
// POST /clusters
func (UnimplementedHandler) CreateCluster(ctx context.Context, req *CreateCluster) (r *CreateClusterResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateLoadBalancer implements createLoadBalancer operation.
//
// 指定したAuto Scaling Groupにロードバランサーを作成します。.
//
// POST /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers
func (UnimplementedHandler) CreateLoadBalancer(ctx context.Context, req *CreateLoadBalancer, params CreateLoadBalancerParams) (r *CreateLoadBalancerResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteApplication implements deleteApplication operation.
//
// 指定したアプリケーションを削除します。
// ## 前提条件
// - 当該アプリケーションに **アクティブなバージョンが存在しない** こと
// - いずれのワーカーノードでも当該アプリケーションの
// **コンテナが稼働していない** こと.
//
// DELETE /applications/{applicationID}
func (UnimplementedHandler) DeleteApplication(ctx context.Context, params DeleteApplicationParams) error {
	return ht.ErrNotImplemented
}

// DeleteApplicationVersion implements deleteApplicationVersion operation.
//
// 現在ノードにデプロイされているバージョンおよびアクティブなバージョンは削除出来ない｡.
//
// DELETE /applications/{applicationID}/versions/{version}
func (UnimplementedHandler) DeleteApplicationVersion(ctx context.Context, params DeleteApplicationVersionParams) error {
	return ht.ErrNotImplemented
}

// DeleteAutoScalingGroup implements deleteAutoScalingGroup operation.
//
// 指定した Auto Scaling Group を削除します。.
//
// DELETE /clusters/{clusterID}/asg/{autoScalingGroupID}
func (UnimplementedHandler) DeleteAutoScalingGroup(ctx context.Context, params DeleteAutoScalingGroupParams) error {
	return ht.ErrNotImplemented
}

// DeleteCertificate implements deleteCertificate operation.
//
// 指定した証明書を削除します。.
//
// DELETE /clusters/{clusterID}/certificates/{certificateID}
func (UnimplementedHandler) DeleteCertificate(ctx context.Context, params DeleteCertificateParams) error {
	return ht.ErrNotImplemented
}

// DeleteCluster implements deleteCluster operation.
//
// 指定したクラスタを削除します。.
//
// DELETE /clusters/{clusterID}
func (UnimplementedHandler) DeleteCluster(ctx context.Context, params DeleteClusterParams) error {
	return ht.ErrNotImplemented
}

// DeleteLoadBalancer implements deleteLoadBalancer operation.
//
// 指定したロードバランサーを削除します。.
//
// DELETE /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}
func (UnimplementedHandler) DeleteLoadBalancer(ctx context.Context, params DeleteLoadBalancerParams) error {
	return ht.ErrNotImplemented
}

// GetApplication implements getApplication operation.
//
// 指定したアプリケーションIDの詳細情報を返します。.
//
// GET /applications/{applicationID}
func (UnimplementedHandler) GetApplication(ctx context.Context, params GetApplicationParams) (r *GetApplicationResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplicationContainers implements getApplicationContainers operation.
//
// 指定したアプリケーションの各ワーカーノード上でのコンテナ配置情報を返します。.
//
// GET /applications/{applicationID}/containers
func (UnimplementedHandler) GetApplicationContainers(ctx context.Context, params GetApplicationContainersParams) (r *GetApplicationContainersResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplicationVersion implements getApplicationVersion operation.
//
// 指定されたバージョンの詳細取得.
//
// GET /applications/{applicationID}/versions/{version}
func (UnimplementedHandler) GetApplicationVersion(ctx context.Context, params GetApplicationVersionParams) (r *GetApplicationVersionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAutoScalingGroup implements getAutoScalingGroup operation.
//
// 指定した Auto Scaling Group の詳細情報を返します。.
//
// GET /clusters/{clusterID}/asg/{autoScalingGroupID}
func (UnimplementedHandler) GetAutoScalingGroup(ctx context.Context, params GetAutoScalingGroupParams) (r *GetAutoScalingGroupResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCertificate implements getCertificate operation.
//
// 指定した証明書の詳細情報を返します。.
//
// GET /clusters/{clusterID}/certificates/{certificateID}
func (UnimplementedHandler) GetCertificate(ctx context.Context, params GetCertificateParams) (r *GetCertificateResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCluster implements getCluster operation.
//
// 指定したクラスタの詳細情報を返します。.
//
// GET /clusters/{clusterID}
func (UnimplementedHandler) GetCluster(ctx context.Context, params GetClusterParams) (r *GetClusterResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLoadBalancer implements getLoadBalancer operation.
//
// 指定したロードバランサーの詳細情報を返します。.
//
// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}
func (UnimplementedHandler) GetLoadBalancer(ctx context.Context, params GetLoadBalancerParams) (r *GetLoadBalancerResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLoadBalancerNode implements getLoadBalancerNode operation.
//
// 指定したロードバランサーノードの詳細情報を返します。.
//
// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}/load_balancer_nodes/{loadBalancerNodeID}
func (UnimplementedHandler) GetLoadBalancerNode(ctx context.Context, params GetLoadBalancerNodeParams) (r *GetLoadBalancerNodeResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkerNode implements getWorkerNode operation.
//
// 指定したワーカーノードの詳細情報を返します。.
//
// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes/{workerNodeID}
func (UnimplementedHandler) GetWorkerNode(ctx context.Context, params GetWorkerNodeParams) (r *GetWorkerNodeResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListApplicationVersions implements listApplicationVersions operation.
//
// 指定されたアプリケーションのバージョン一覧取得.
//
// GET /applications/{applicationID}/versions
func (UnimplementedHandler) ListApplicationVersions(ctx context.Context, params ListApplicationVersionsParams) (r *ListApplicationVersionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListApplications implements listApplications operation.
//
// 指定したアカウントに紐づくアプリケーションの一覧を返します。.
//
// GET /applications
func (UnimplementedHandler) ListApplications(ctx context.Context, params ListApplicationsParams) (r *ListApplicationResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAutoScalingGroups implements listAutoScalingGroups operation.
//
// クラスタに所属する Auto Scaling Group
// の一覧を返します。ページネーションに対応します。.
//
// GET /clusters/{clusterID}/asg
func (UnimplementedHandler) ListAutoScalingGroups(ctx context.Context, params ListAutoScalingGroupsParams) (r *ListAutoScalingGroupResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCertificate implements listCertificate operation.
//
// クラスタ内の証明書一覧を返します。ページネーションに対応します。.
//
// GET /clusters/{clusterID}/certificates
func (UnimplementedHandler) ListCertificate(ctx context.Context, params ListCertificateParams) (r *ListCertificateResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListClusters implements listClusters operation.
//
// アカウントに紐づくクラスタの一覧を返します。ページネーションに対応します。.
//
// GET /clusters
func (UnimplementedHandler) ListClusters(ctx context.Context, params ListClustersParams) (r *ListClusterResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLbServiceClasses implements listLbServiceClasses operation.
//
// ロードバランサ用のサービスクラス一覧を返します。.
//
// GET /service_classes/lb
func (UnimplementedHandler) ListLbServiceClasses(ctx context.Context) (r *ListLbServiceClassResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLoadBalancerNodes implements listLoadBalancerNodes operation.
//
// 指定したロードバランサーに属するノードの一覧を返します。.
//
// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}/load_balancer_nodes
func (UnimplementedHandler) ListLoadBalancerNodes(ctx context.Context, params ListLoadBalancerNodesParams) (r *ListLoadBalancerNodesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLoadBalancers implements listLoadBalancers operation.
//
// Auto Scaling Group
// に属するロードバランサーの一覧を返します。ページネーションに対応します。.
//
// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers
func (UnimplementedHandler) ListLoadBalancers(ctx context.Context, params ListLoadBalancersParams) (r *ListLoadBalancersResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkerNodes implements listWorkerNodes operation.
//
// Auto Scaling Group
// に所属するワーカーノードの一覧を返します。ページネーションに対応します。.
//
// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes
func (UnimplementedHandler) ListWorkerNodes(ctx context.Context, params ListWorkerNodesParams) (r *ListWorkerNodesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkerServiceClasses implements listWorkerServiceClasses operation.
//
// ワーカーノード用のサービスクラス一覧を返します。.
//
// GET /service_classes/worker
func (UnimplementedHandler) ListWorkerServiceClasses(ctx context.Context) (r *ListWorkerServiceClassResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateApplication implements updateApplication operation.
//
// アプリケーションのactiveVersionなどを更新します。クラスタの変更はできません。activeVersionを変更すると指定したバージョンがデプロイされます。activeVersionをnullにするとアプリケーションは非アクティブ状態になり､デプロイされなくなります。アプリケーション削除前には activeVersion を null にする必要があります｡.
//
// PUT /applications/{applicationID}
func (UnimplementedHandler) UpdateApplication(ctx context.Context, req *UpdateApplication, params UpdateApplicationParams) error {
	return ht.ErrNotImplemented
}

// UpdateCertificate implements updateCertificate operation.
//
// 指定した証明書を更新します。.
//
// PUT /clusters/{clusterID}/certificates/{certificateID}
func (UnimplementedHandler) UpdateCertificate(ctx context.Context, req *UpdateCertificate, params UpdateCertificateParams) error {
	return ht.ErrNotImplemented
}

// UpdateCluster implements updateCluster operation.
//
// 指定したクラスタの設定を更新します。.
//
// PUT /clusters/{clusterID}
func (UnimplementedHandler) UpdateCluster(ctx context.Context, req *UpdateCluster, params UpdateClusterParams) error {
	return ht.ErrNotImplemented
}

// UpdateWorkerNodeDrainingState implements updateWorkerNodeDrainingState operation.
//
// 指定したワーカーノードのdraining状態を更新します（draining
// を有効/無効にします）。.
//
// PUT /clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes/{workerNodeID}/draining
func (UnimplementedHandler) UpdateWorkerNodeDrainingState(ctx context.Context, req *UpdateWorkerNodeDrainingRequest, params UpdateWorkerNodeDrainingStateParams) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
