// Code generated by ogen, DO NOT EDIT.

package apprun

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [4]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "applications"

				if l := len("applications"); len(elem) >= l && elem[0:l] == "applications" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListApplicationsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateApplicationRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "applicationID"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteApplicationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetApplicationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateApplicationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "DELETE,GET,PUT")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "containers"

							if l := len("containers"); len(elem) >= l && elem[0:l] == "containers" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetApplicationContainersRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 'v': // Prefix: "versions"

							if l := len("versions"); len(elem) >= l && elem[0:l] == "versions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListApplicationVersionsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateApplicationVersionRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET,POST")
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "version"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleDeleteApplicationVersionRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetApplicationVersionRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "DELETE,GET")
									}

									return
								}

							}

						}

					}

				}

			case 'c': // Prefix: "clusters"

				if l := len("clusters"); len(elem) >= l && elem[0:l] == "clusters" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListClustersRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateClusterRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "clusterID"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteClusterRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetClusterRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateClusterRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "DELETE,GET,PUT")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "asg"

							if l := len("asg"); len(elem) >= l && elem[0:l] == "asg" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListAutoScalingGroupsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateAutoScalingGroupRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET,POST")
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "autoScalingGroupID"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch r.Method {
									case "DELETE":
										s.handleDeleteAutoScalingGroupRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetAutoScalingGroupRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "DELETE,GET")
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'l': // Prefix: "load_balancers"

										if l := len("load_balancers"); len(elem) >= l && elem[0:l] == "load_balancers" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch r.Method {
											case "GET":
												s.handleListLoadBalancersRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											case "POST":
												s.handleCreateLoadBalancerRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "GET,POST")
											}

											return
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "loadBalancerID"
											// Match until "/"
											idx := strings.IndexByte(elem, '/')
											if idx < 0 {
												idx = len(elem)
											}
											args[2] = elem[:idx]
											elem = elem[idx:]

											if len(elem) == 0 {
												switch r.Method {
												case "DELETE":
													s.handleDeleteLoadBalancerRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												case "GET":
													s.handleGetLoadBalancerRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "DELETE,GET")
												}

												return
											}
											switch elem[0] {
											case '/': // Prefix: "/load_balancer_nodes"

												if l := len("/load_balancer_nodes"); len(elem) >= l && elem[0:l] == "/load_balancer_nodes" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													switch r.Method {
													case "GET":
														s.handleListLoadBalancerNodesRequest([3]string{
															args[0],
															args[1],
															args[2],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, "GET")
													}

													return
												}
												switch elem[0] {
												case '/': // Prefix: "/"

													if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
														elem = elem[l:]
													} else {
														break
													}

													// Param: "loadBalancerNodeID"
													// Leaf parameter, slashes are prohibited
													idx := strings.IndexByte(elem, '/')
													if idx >= 0 {
														break
													}
													args[3] = elem
													elem = ""

													if len(elem) == 0 {
														// Leaf node.
														switch r.Method {
														case "GET":
															s.handleGetLoadBalancerNodeRequest([4]string{
																args[0],
																args[1],
																args[2],
																args[3],
															}, elemIsEscaped, w, r)
														default:
															s.notAllowed(w, r, "GET")
														}

														return
													}

												}

											}

										}

									case 'w': // Prefix: "worker_nodes"

										if l := len("worker_nodes"); len(elem) >= l && elem[0:l] == "worker_nodes" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch r.Method {
											case "GET":
												s.handleListWorkerNodesRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "GET")
											}

											return
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "workerNodeID"
											// Match until "/"
											idx := strings.IndexByte(elem, '/')
											if idx < 0 {
												idx = len(elem)
											}
											args[2] = elem[:idx]
											elem = elem[idx:]

											if len(elem) == 0 {
												switch r.Method {
												case "GET":
													s.handleGetWorkerNodeRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "GET")
												}

												return
											}
											switch elem[0] {
											case '/': // Prefix: "/draining"

												if l := len("/draining"); len(elem) >= l && elem[0:l] == "/draining" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch r.Method {
													case "PUT":
														s.handleUpdateWorkerNodeDrainingStateRequest([3]string{
															args[0],
															args[1],
															args[2],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, "PUT")
													}

													return
												}

											}

										}

									}

								}

							}

						case 'c': // Prefix: "certificates"

							if l := len("certificates"); len(elem) >= l && elem[0:l] == "certificates" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListCertificateRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateCertificateRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET,POST")
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "certificateID"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleDeleteCertificateRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetCertificateRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "PUT":
										s.handleUpdateCertificateRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "DELETE,GET,PUT")
									}

									return
								}

							}

						}

					}

				}

			case 's': // Prefix: "service_classes/"

				if l := len("service_classes/"); len(elem) >= l && elem[0:l] == "service_classes/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'l': // Prefix: "lb"

					if l := len("lb"); len(elem) >= l && elem[0:l] == "lb" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleListLbServiceClassesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				case 'w': // Prefix: "worker"

					if l := len("worker"); len(elem) >= l && elem[0:l] == "worker" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleListWorkerServiceClassesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [4]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "applications"

				if l := len("applications"); len(elem) >= l && elem[0:l] == "applications" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListApplicationsOperation
						r.summary = "アカウント内のアプリケーション一覧の取得"
						r.operationID = "listApplications"
						r.operationGroup = ""
						r.pathPattern = "/applications"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateApplicationOperation
						r.summary = "新しいアプリケーションの作成"
						r.operationID = "createApplication"
						r.operationGroup = ""
						r.pathPattern = "/applications"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "applicationID"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteApplicationOperation
							r.summary = "アプリケーションの削除"
							r.operationID = "deleteApplication"
							r.operationGroup = ""
							r.pathPattern = "/applications/{applicationID}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetApplicationOperation
							r.summary = "アプリケーションの詳細情報を取得する"
							r.operationID = "getApplication"
							r.operationGroup = ""
							r.pathPattern = "/applications/{applicationID}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateApplicationOperation
							r.summary = "アプリケーション情報の更新"
							r.operationID = "updateApplication"
							r.operationGroup = ""
							r.pathPattern = "/applications/{applicationID}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "containers"

							if l := len("containers"); len(elem) >= l && elem[0:l] == "containers" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetApplicationContainersOperation
									r.summary = "アプリケーションのノードごとのコンテナ配置情報を取得"
									r.operationID = "getApplicationContainers"
									r.operationGroup = ""
									r.pathPattern = "/applications/{applicationID}/containers"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'v': // Prefix: "versions"

							if l := len("versions"); len(elem) >= l && elem[0:l] == "versions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListApplicationVersionsOperation
									r.summary = "アプリケーションバージョン一覧の取得"
									r.operationID = "listApplicationVersions"
									r.operationGroup = ""
									r.pathPattern = "/applications/{applicationID}/versions"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateApplicationVersionOperation
									r.summary = "アプリケーションバージョンの作成"
									r.operationID = "createApplicationVersion"
									r.operationGroup = ""
									r.pathPattern = "/applications/{applicationID}/versions"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "version"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = DeleteApplicationVersionOperation
										r.summary = "アプリケーションバージョンの削除"
										r.operationID = "deleteApplicationVersion"
										r.operationGroup = ""
										r.pathPattern = "/applications/{applicationID}/versions/{version}"
										r.args = args
										r.count = 2
										return r, true
									case "GET":
										r.name = GetApplicationVersionOperation
										r.summary = "アプリケーションバージョンの詳細取得"
										r.operationID = "getApplicationVersion"
										r.operationGroup = ""
										r.pathPattern = "/applications/{applicationID}/versions/{version}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				}

			case 'c': // Prefix: "clusters"

				if l := len("clusters"); len(elem) >= l && elem[0:l] == "clusters" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListClustersOperation
						r.summary = "クラスタの一覧の取得"
						r.operationID = "listClusters"
						r.operationGroup = ""
						r.pathPattern = "/clusters"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateClusterOperation
						r.summary = "クラスタの作成"
						r.operationID = "createCluster"
						r.operationGroup = ""
						r.pathPattern = "/clusters"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "clusterID"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteClusterOperation
							r.summary = "クラスタの削除"
							r.operationID = "deleteCluster"
							r.operationGroup = ""
							r.pathPattern = "/clusters/{clusterID}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetClusterOperation
							r.summary = "クラスタの詳細の取得"
							r.operationID = "getCluster"
							r.operationGroup = ""
							r.pathPattern = "/clusters/{clusterID}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateClusterOperation
							r.summary = "クラスタの更新"
							r.operationID = "updateCluster"
							r.operationGroup = ""
							r.pathPattern = "/clusters/{clusterID}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "asg"

							if l := len("asg"); len(elem) >= l && elem[0:l] == "asg" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListAutoScalingGroupsOperation
									r.summary = "Auto Scaling Groupの一覧を取得"
									r.operationID = "listAutoScalingGroups"
									r.operationGroup = ""
									r.pathPattern = "/clusters/{clusterID}/asg"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateAutoScalingGroupOperation
									r.summary = "Auto Scaling Groupの作成"
									r.operationID = "createAutoScalingGroup"
									r.operationGroup = ""
									r.pathPattern = "/clusters/{clusterID}/asg"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "autoScalingGroupID"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch method {
									case "DELETE":
										r.name = DeleteAutoScalingGroupOperation
										r.summary = "Auto Scaling Groupの削除"
										r.operationID = "deleteAutoScalingGroup"
										r.operationGroup = ""
										r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}"
										r.args = args
										r.count = 2
										return r, true
									case "GET":
										r.name = GetAutoScalingGroupOperation
										r.summary = "Auto Scaling Groupの詳細を取得"
										r.operationID = "getAutoScalingGroup"
										r.operationGroup = ""
										r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'l': // Prefix: "load_balancers"

										if l := len("load_balancers"); len(elem) >= l && elem[0:l] == "load_balancers" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch method {
											case "GET":
												r.name = ListLoadBalancersOperation
												r.summary = "ロードバランサーの一覧を取得"
												r.operationID = "listLoadBalancers"
												r.operationGroup = ""
												r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers"
												r.args = args
												r.count = 2
												return r, true
											case "POST":
												r.name = CreateLoadBalancerOperation
												r.summary = "ロードバランサーの作成"
												r.operationID = "createLoadBalancer"
												r.operationGroup = ""
												r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "loadBalancerID"
											// Match until "/"
											idx := strings.IndexByte(elem, '/')
											if idx < 0 {
												idx = len(elem)
											}
											args[2] = elem[:idx]
											elem = elem[idx:]

											if len(elem) == 0 {
												switch method {
												case "DELETE":
													r.name = DeleteLoadBalancerOperation
													r.summary = "ロードバランサーを削除する"
													r.operationID = "deleteLoadBalancer"
													r.operationGroup = ""
													r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}"
													r.args = args
													r.count = 3
													return r, true
												case "GET":
													r.name = GetLoadBalancerOperation
													r.summary = "ロードバランサーの詳細を取得"
													r.operationID = "getLoadBalancer"
													r.operationGroup = ""
													r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}"
													r.args = args
													r.count = 3
													return r, true
												default:
													return
												}
											}
											switch elem[0] {
											case '/': // Prefix: "/load_balancer_nodes"

												if l := len("/load_balancer_nodes"); len(elem) >= l && elem[0:l] == "/load_balancer_nodes" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													switch method {
													case "GET":
														r.name = ListLoadBalancerNodesOperation
														r.summary = "ロードバランサーノードの一覧を取得"
														r.operationID = "listLoadBalancerNodes"
														r.operationGroup = ""
														r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}/load_balancer_nodes"
														r.args = args
														r.count = 3
														return r, true
													default:
														return
													}
												}
												switch elem[0] {
												case '/': // Prefix: "/"

													if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
														elem = elem[l:]
													} else {
														break
													}

													// Param: "loadBalancerNodeID"
													// Leaf parameter, slashes are prohibited
													idx := strings.IndexByte(elem, '/')
													if idx >= 0 {
														break
													}
													args[3] = elem
													elem = ""

													if len(elem) == 0 {
														// Leaf node.
														switch method {
														case "GET":
															r.name = GetLoadBalancerNodeOperation
															r.summary = "ロードバランサーノードの詳細情報を取得"
															r.operationID = "getLoadBalancerNode"
															r.operationGroup = ""
															r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}/load_balancer_nodes/{loadBalancerNodeID}"
															r.args = args
															r.count = 4
															return r, true
														default:
															return
														}
													}

												}

											}

										}

									case 'w': // Prefix: "worker_nodes"

										if l := len("worker_nodes"); len(elem) >= l && elem[0:l] == "worker_nodes" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch method {
											case "GET":
												r.name = ListWorkerNodesOperation
												r.summary = "Auto Scaling Group に所属するワーカーノード一覧を取得"
												r.operationID = "listWorkerNodes"
												r.operationGroup = ""
												r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "workerNodeID"
											// Match until "/"
											idx := strings.IndexByte(elem, '/')
											if idx < 0 {
												idx = len(elem)
											}
											args[2] = elem[:idx]
											elem = elem[idx:]

											if len(elem) == 0 {
												switch method {
												case "GET":
													r.name = GetWorkerNodeOperation
													r.summary = "Auto Scaling Group に所属するワーカーノードの詳細を取得"
													r.operationID = "getWorkerNode"
													r.operationGroup = ""
													r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes/{workerNodeID}"
													r.args = args
													r.count = 3
													return r, true
												default:
													return
												}
											}
											switch elem[0] {
											case '/': // Prefix: "/draining"

												if l := len("/draining"); len(elem) >= l && elem[0:l] == "/draining" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch method {
													case "PUT":
														r.name = UpdateWorkerNodeDrainingStateOperation
														r.summary = "ワーカーノードのdraining状態を変更する"
														r.operationID = "updateWorkerNodeDrainingState"
														r.operationGroup = ""
														r.pathPattern = "/clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes/{workerNodeID}/draining"
														r.args = args
														r.count = 3
														return r, true
													default:
														return
													}
												}

											}

										}

									}

								}

							}

						case 'c': // Prefix: "certificates"

							if l := len("certificates"); len(elem) >= l && elem[0:l] == "certificates" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListCertificateOperation
									r.summary = "証明書の一覧を取得"
									r.operationID = "listCertificate"
									r.operationGroup = ""
									r.pathPattern = "/clusters/{clusterID}/certificates"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateCertificateOperation
									r.summary = "証明書の作成"
									r.operationID = "createCertificate"
									r.operationGroup = ""
									r.pathPattern = "/clusters/{clusterID}/certificates"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "certificateID"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = DeleteCertificateOperation
										r.summary = "証明書の削除"
										r.operationID = "deleteCertificate"
										r.operationGroup = ""
										r.pathPattern = "/clusters/{clusterID}/certificates/{certificateID}"
										r.args = args
										r.count = 2
										return r, true
									case "GET":
										r.name = GetCertificateOperation
										r.summary = "証明書の詳細を取得"
										r.operationID = "getCertificate"
										r.operationGroup = ""
										r.pathPattern = "/clusters/{clusterID}/certificates/{certificateID}"
										r.args = args
										r.count = 2
										return r, true
									case "PUT":
										r.name = UpdateCertificateOperation
										r.summary = "証明書の更新"
										r.operationID = "updateCertificate"
										r.operationGroup = ""
										r.pathPattern = "/clusters/{clusterID}/certificates/{certificateID}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				}

			case 's': // Prefix: "service_classes/"

				if l := len("service_classes/"); len(elem) >= l && elem[0:l] == "service_classes/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'l': // Prefix: "lb"

					if l := len("lb"); len(elem) >= l && elem[0:l] == "lb" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ListLbServiceClassesOperation
							r.summary = "ロードバランササービスクラス一覧"
							r.operationID = "listLbServiceClasses"
							r.operationGroup = ""
							r.pathPattern = "/service_classes/lb"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'w': // Prefix: "worker"

					if l := len("worker"); len(elem) >= l && elem[0:l] == "worker" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ListWorkerServiceClassesOperation
							r.summary = "ワーカノードサービスクラス一覧"
							r.operationID = "listWorkerServiceClasses"
							r.operationGroup = ""
							r.pathPattern = "/service_classes/worker"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			}

		}
	}
	return r, false
}
