// Code generated by ogen, DO NOT EDIT.

package apprun

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateApplication implements createApplication operation.
	//
	// 指定したクラスタに新しいアプリケーションを作成します。1アカウントにつき最大10個まで作成可能です。.
	//
	// POST /applications
	CreateApplication(ctx context.Context, req *CreateApplication) (*CreateApplicationResponse, error)
	// CreateApplicationVersion implements createApplicationVersion operation.
	//
	// アプリケーションバージョンを作成します｡アプリケーションバージョンを作成するだけではノードにデプロイされません｡アプリケーションのアクティブバージョンに指定するとノードにデプロイされます｡.
	//
	// POST /applications/{applicationID}/versions
	CreateApplicationVersion(ctx context.Context, req *CreateApplicationVersion, params CreateApplicationVersionParams) (*CreateApplicationVersionResponse, error)
	// CreateAutoScalingGroup implements createAutoScalingGroup operation.
	//
	// 新しい Auto Scaling Group を作成します。.
	//
	// POST /clusters/{clusterID}/asg
	CreateAutoScalingGroup(ctx context.Context, req *CreateAutoScalingGroup, params CreateAutoScalingGroupParams) (*CreateAutoScalingGroupResponse, error)
	// CreateCertificate implements createCertificate operation.
	//
	// 新しい証明書を作成します。.
	//
	// POST /clusters/{clusterID}/certificates
	CreateCertificate(ctx context.Context, req *CreateCertificate, params CreateCertificateParams) (*CreateCertificateResponse, error)
	// CreateCluster implements createCluster operation.
	//
	// 新しいクラスタを作成します。作成後にクラスタIDを返します。.
	//
	// POST /clusters
	CreateCluster(ctx context.Context, req *CreateCluster) (*CreateClusterResponse, error)
	// CreateLoadBalancer implements createLoadBalancer operation.
	//
	// 指定したAuto Scaling Groupにロードバランサーを作成します。.
	//
	// POST /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers
	CreateLoadBalancer(ctx context.Context, req *CreateLoadBalancer, params CreateLoadBalancerParams) (*CreateLoadBalancerResponse, error)
	// DeleteApplication implements deleteApplication operation.
	//
	// 指定したアプリケーションを削除します。
	// ## 前提条件
	// - 当該アプリケーションに **アクティブなバージョンが存在しない** こと
	// - いずれのワーカーノードでも当該アプリケーションの
	// **コンテナが稼働していない** こと.
	//
	// DELETE /applications/{applicationID}
	DeleteApplication(ctx context.Context, params DeleteApplicationParams) error
	// DeleteApplicationVersion implements deleteApplicationVersion operation.
	//
	// 現在ノードにデプロイされているバージョンおよびアクティブなバージョンは削除出来ない｡.
	//
	// DELETE /applications/{applicationID}/versions/{version}
	DeleteApplicationVersion(ctx context.Context, params DeleteApplicationVersionParams) error
	// DeleteAutoScalingGroup implements deleteAutoScalingGroup operation.
	//
	// 指定した Auto Scaling Group を削除します。.
	//
	// DELETE /clusters/{clusterID}/asg/{autoScalingGroupID}
	DeleteAutoScalingGroup(ctx context.Context, params DeleteAutoScalingGroupParams) error
	// DeleteCertificate implements deleteCertificate operation.
	//
	// 指定した証明書を削除します。.
	//
	// DELETE /clusters/{clusterID}/certificates/{certificateID}
	DeleteCertificate(ctx context.Context, params DeleteCertificateParams) error
	// DeleteCluster implements deleteCluster operation.
	//
	// 指定したクラスタを削除します。.
	//
	// DELETE /clusters/{clusterID}
	DeleteCluster(ctx context.Context, params DeleteClusterParams) error
	// DeleteLoadBalancer implements deleteLoadBalancer operation.
	//
	// 指定したロードバランサーを削除します。.
	//
	// DELETE /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}
	DeleteLoadBalancer(ctx context.Context, params DeleteLoadBalancerParams) error
	// GetApplication implements getApplication operation.
	//
	// 指定したアプリケーションIDの詳細情報を返します。.
	//
	// GET /applications/{applicationID}
	GetApplication(ctx context.Context, params GetApplicationParams) (*GetApplicationResponse, error)
	// GetApplicationContainers implements getApplicationContainers operation.
	//
	// 指定したアプリケーションの各ワーカーノード上でのコンテナ配置情報を返します。.
	//
	// GET /applications/{applicationID}/containers
	GetApplicationContainers(ctx context.Context, params GetApplicationContainersParams) (*GetApplicationContainersResponse, error)
	// GetApplicationVersion implements getApplicationVersion operation.
	//
	// 指定されたバージョンの詳細取得.
	//
	// GET /applications/{applicationID}/versions/{version}
	GetApplicationVersion(ctx context.Context, params GetApplicationVersionParams) (*GetApplicationVersionResponse, error)
	// GetAutoScalingGroup implements getAutoScalingGroup operation.
	//
	// 指定した Auto Scaling Group の詳細情報を返します。.
	//
	// GET /clusters/{clusterID}/asg/{autoScalingGroupID}
	GetAutoScalingGroup(ctx context.Context, params GetAutoScalingGroupParams) (*GetAutoScalingGroupResponse, error)
	// GetCertificate implements getCertificate operation.
	//
	// 指定した証明書の詳細情報を返します。.
	//
	// GET /clusters/{clusterID}/certificates/{certificateID}
	GetCertificate(ctx context.Context, params GetCertificateParams) (*GetCertificateResponse, error)
	// GetCluster implements getCluster operation.
	//
	// 指定したクラスタの詳細情報を返します。.
	//
	// GET /clusters/{clusterID}
	GetCluster(ctx context.Context, params GetClusterParams) (*GetClusterResponse, error)
	// GetLoadBalancer implements getLoadBalancer operation.
	//
	// 指定したロードバランサーの詳細情報を返します。.
	//
	// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}
	GetLoadBalancer(ctx context.Context, params GetLoadBalancerParams) (*GetLoadBalancerResponse, error)
	// GetLoadBalancerNode implements getLoadBalancerNode operation.
	//
	// 指定したロードバランサーノードの詳細情報を返します。.
	//
	// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}/load_balancer_nodes/{loadBalancerNodeID}
	GetLoadBalancerNode(ctx context.Context, params GetLoadBalancerNodeParams) (*GetLoadBalancerNodeResponse, error)
	// GetWorkerNode implements getWorkerNode operation.
	//
	// 指定したワーカーノードの詳細情報を返します。.
	//
	// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes/{workerNodeID}
	GetWorkerNode(ctx context.Context, params GetWorkerNodeParams) (*GetWorkerNodeResponse, error)
	// ListApplicationVersions implements listApplicationVersions operation.
	//
	// 指定されたアプリケーションのバージョン一覧取得.
	//
	// GET /applications/{applicationID}/versions
	ListApplicationVersions(ctx context.Context, params ListApplicationVersionsParams) (*ListApplicationVersionResponse, error)
	// ListApplications implements listApplications operation.
	//
	// 指定したアカウントに紐づくアプリケーションの一覧を返します。.
	//
	// GET /applications
	ListApplications(ctx context.Context, params ListApplicationsParams) (*ListApplicationResponse, error)
	// ListAutoScalingGroups implements listAutoScalingGroups operation.
	//
	// クラスタに所属する Auto Scaling Group
	// の一覧を返します。ページネーションに対応します。.
	//
	// GET /clusters/{clusterID}/asg
	ListAutoScalingGroups(ctx context.Context, params ListAutoScalingGroupsParams) (*ListAutoScalingGroupResponse, error)
	// ListCertificate implements listCertificate operation.
	//
	// クラスタ内の証明書一覧を返します。ページネーションに対応します。.
	//
	// GET /clusters/{clusterID}/certificates
	ListCertificate(ctx context.Context, params ListCertificateParams) (*ListCertificateResponse, error)
	// ListClusters implements listClusters operation.
	//
	// アカウントに紐づくクラスタの一覧を返します。ページネーションに対応します。.
	//
	// GET /clusters
	ListClusters(ctx context.Context, params ListClustersParams) (*ListClusterResponse, error)
	// ListLbServiceClasses implements listLbServiceClasses operation.
	//
	// ロードバランサ用のサービスクラス一覧を返します。.
	//
	// GET /service_classes/lb
	ListLbServiceClasses(ctx context.Context) (*ListLbServiceClassResponse, error)
	// ListLoadBalancerNodes implements listLoadBalancerNodes operation.
	//
	// 指定したロードバランサーに属するノードの一覧を返します。.
	//
	// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers/{loadBalancerID}/load_balancer_nodes
	ListLoadBalancerNodes(ctx context.Context, params ListLoadBalancerNodesParams) (*ListLoadBalancerNodesResponse, error)
	// ListLoadBalancers implements listLoadBalancers operation.
	//
	// Auto Scaling Group
	// に属するロードバランサーの一覧を返します。ページネーションに対応します。.
	//
	// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers
	ListLoadBalancers(ctx context.Context, params ListLoadBalancersParams) (*ListLoadBalancersResponse, error)
	// ListWorkerNodes implements listWorkerNodes operation.
	//
	// Auto Scaling Group
	// に所属するワーカーノードの一覧を返します。ページネーションに対応します。.
	//
	// GET /clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes
	ListWorkerNodes(ctx context.Context, params ListWorkerNodesParams) (*ListWorkerNodesResponse, error)
	// ListWorkerServiceClasses implements listWorkerServiceClasses operation.
	//
	// ワーカーノード用のサービスクラス一覧を返します。.
	//
	// GET /service_classes/worker
	ListWorkerServiceClasses(ctx context.Context) (*ListWorkerServiceClassResponse, error)
	// UpdateApplication implements updateApplication operation.
	//
	// アプリケーションのactiveVersionなどを更新します。クラスタの変更はできません。activeVersionを変更すると指定したバージョンがデプロイされます。activeVersionをnullにするとアプリケーションは非アクティブ状態になり､デプロイされなくなります。アプリケーション削除前には activeVersion を null にする必要があります｡.
	//
	// PUT /applications/{applicationID}
	UpdateApplication(ctx context.Context, req *UpdateApplication, params UpdateApplicationParams) error
	// UpdateCertificate implements updateCertificate operation.
	//
	// 指定した証明書を更新します。.
	//
	// PUT /clusters/{clusterID}/certificates/{certificateID}
	UpdateCertificate(ctx context.Context, req *UpdateCertificate, params UpdateCertificateParams) error
	// UpdateCluster implements updateCluster operation.
	//
	// 指定したクラスタの設定を更新します。.
	//
	// PUT /clusters/{clusterID}
	UpdateCluster(ctx context.Context, req *UpdateCluster, params UpdateClusterParams) error
	// UpdateWorkerNodeDrainingState implements updateWorkerNodeDrainingState operation.
	//
	// 指定したワーカーノードのdraining状態を更新します（draining
	// を有効/無効にします）。.
	//
	// PUT /clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes/{workerNodeID}/draining
	UpdateWorkerNodeDrainingState(ctx context.Context, req *UpdateWorkerNodeDrainingRequest, params UpdateWorkerNodeDrainingStateParams) error
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
